### ISSUE TITLE
Not really an issue...

### ISSUE THREAD

**Issue by AceAutomation** [Bouni/ModBusGateway#1]
Hi Bouni,
I hope you will read my post.
I'm trying to update the code for the USB port instead of the serial port for Raspberry Pi 0.
So, I don't use the  Waveshare CAN RS485 Cape.
On the Ethernet side, socket work (Now with 5002 as port number (>1024).. I will check after for 502)
But for the USB port, that doesn't work. I'm trying to change : 
- port=/dev/ttyACM0
But I saw, I must change also your py code.
I'll look... but if you have any suggestions.. or more..
Thanks
Have a good continuation
Rémi

**Comment by AceAutomation** [comment]
And for your information:

2018-04-04 16:29:32,756: DEBUG    - Serial Connection open
----------------------------------------
Exception happened during processing of request from ('192.168.111.37', 56418)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 650, in __init__
    self.setup()
  File "modbus-gateway.py", line 19, in setup
    self.serial_config()
  File "modbus-gateway.py", line 37, in serial_config
    fcntl.ioctl(self.serial.fileno(), 0x542F, RS485_CONFIG)
IOError: [Errno 25] Inappropriate ioctl for device
----------------------------------------

And the Virtual driver I've on the USB port = ttyACM0  (It work with MinimalModbus : Python Package)
My device I read is slave Modbus on its USB port. (see aceautomation.eu)

[ 1786.046136] usb 1-1: New USB device found, idVendor=1cbe, idProduct=0002
[ 1786.046153] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 1786.046160] usb 1-1: Product: Virtual COM Port
[ 1786.046167] usb 1-1: Manufacturer: VelocioNetworks
[ 1786.046173] usb 1-1: SerialNumber: 12345678
[ 1786.205412] cdc_acm 1-1:1.0: **ttyACM0**: USB ACM device
[ 1786.225933] usbcore: registered new interface driver cdc_acm
[ 1786.225945] cdc_acm: USB Abstract Control Model driver for USB modems and ISDN adapters

**Comment by AceAutomation** [comment]
That works now... Thanks 👍
